spring.application.name=com.proyecto.api

#mysql
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port = 9002


#Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/