package com.proyecto.api.enums;

public enum CategoriasEnum {

	SOPORTE_TECNICO,
	SOFTWARE,
	HARDWARE,
	BASE_DE_DATOS, 
	MANTENIMIENTO, // MANTENIMIENTO DE EQUIPOS
	ACCESO_CUENTAS,	// USUARIOS BLOQUEADOS, SOLICITUDES DE ACCESO
	INCIDENCIA // CAIDAS DEL SISTEMA, ERRORES CRITICOS
}
